spring.application.name=looking

server.port=8080
server.servlet.session.timeout=30m
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax

# ==============================
# MySQL
# ==============================
spring.datasource.url=jdbc:mysql://localhost:3306/lookingBDV01?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==============================
# JPA / Hibernate
# ==============================
spring.jpa.hibernate.ddl-auto=update
#==># Met a jour les tables automatiquement sans supprimer les donn�es
spring.jpa.show-sql=true
#==># Affiche les requetes SQL dans la console
spring.jpa.properties.hibernate.format_sql=true

# ==============================
# JWT
# ==============================
#powershell
#[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String("SHlwZXJDbG91ZA=="))
#[Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes("TaPhraseSecreteIci"))
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
#==> c un cle secrte ==> singature  ==> qui nous avons utiliser dans toekn
app.jwt.expiration=86400000 
# Token expir� ? ms  ?  Spring retourne 401

# ==============================
# Password reset email
# ==============================
# Frontend reset URL example: http://localhost:4200/reset-password
app.password-reset.frontend-url=http://localhost:4200/reset-password

# Configure your SMTP provider here for real email delivery.
# spring.mail.host=smtp.gmail.com
# spring.mail.port=587
# spring.mail.username=your-email@gmail.com
# spring.mail.password=your-app-password
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:rzouga.chamek@gmail.com}
spring.mail.password=${MAIL_PASSWORD:qeqb wgus uqtv igos}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Mail sender identity (use a valid domain, apostrophes are not allowed in domain names)
app.mail.from-address=${MAIL_FROM_ADDRESS:no-reply@tunisia-tour.tn}
app.mail.from-name=${MAIL_FROM_NAME:TunisiaTour}

# ==============================
# Face AI service (FastAPI)
# ==============================
face.ai.base-url=${FACE_AI_BASE_URL:http://localhost:8001}