spring.application.name=looking

server.port=8080

# ==============================
# MySQL
# ==============================
spring.datasource.url=jdbc:mysql://localhost:3306/lookingBDV01?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==============================
# JPA / Hibernate
# ==============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==============================
# JWT
# ==============================
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration=86400000
# Jackson
# ==============================
spring.jackson.serialization.fail-on-empty-beans=false
spring.jpa.open-in-view=false

# ==============================
# API Keys
# ==============================
groq.correction.api.key=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
groq.api.key=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
huggingface.api.token=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
tavily.api.key=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